version: '3'
services:
    quize_de_pon_db:
        image: mariadb:10.6.4
        container_name: 'quize_de_pon_db'
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/my.cnf:/etc/mysql/mariadb.conf.d/custom.cnf
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: quize_de_pon
            MARIADB_USER: patao
            MARIADB_PASSWORD: patao
            TZ: 'Asia/Tokyo'
        networks:
            - quize_de_pon_network
    quize_de_pon_php_app:
        build: ./docker
        container_name: 'quize_de_pon_php_app'
        volumes:
            - .:/var/www/html
            - ./docker/apache/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
        ports:
            - '8081:80'
        networks:
            - proxy_network
            - quize_de_pon_network
networks:
    proxy_network:
        external: true
    quize_de_pon_network:
