version: '3'
services:
    quize_de_pon_db:
        image: mariadb
        container_name: 'quize_de_pon_db'
        volumes:
            - ./docker/db/data:/var/lib/mysql
            # - ./docker/db/my.conf:/etc/mysql/conf.d/my.conf
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: quize_de_pon
            MYSQL_USER: patao
            MYSQL_PASSWORD: patao
            TZ: 'Asia/Tokyo'
        networks:
            - quize_de_pon_network
    quize_de_pon_php_app:
        build: ./docker
        container_name: 'quize_de_pon_php_app'
        volumes:
            - .:/var/www/html
            - ./docker/apache/virtual.conf:/etc/apache2/conf-enabled/vhost.conf
        ports:
            - '8080:80'
        networks:
            - proxy_network
            - quize_de_pon_network
networks:
    proxy_network:
        external: true
    quize_de_pon_network:
